language: go

dist: xenial

go: 1.17.x

notifications:
  email: true

branches:
  only:
    - main

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install python
  - nvm install 14
  - npm install -g npm@8.x

install:
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - make travis-ci
  
before_deploy:
 - pip install --user bump2version
 - npm install @semantic-release/changelog
 - npm install @semantic-release/exec
 - npm install @semantic-release/git
 - npm install @semantic-release/github
 
deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: main
